# Tasca 4: Pràctica amb programació numèrica

In [18]:
import numpy as np 
from numpy import random as rnd

## Exercici 1
__Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.__

In [19]:
def est_array_1d(array):
    try:
        if array.ndim > 1:
            print("Error: l'input ha de ser un Array d'una dimensió")
        else:
            print("La longitut de l'array és de {} elements".format(len(array)))
            print("El màxim de l'array és {}".format(array.max()))
            print("El mínim de l'array és {}".format(array.min()))
            print("La mitjana aritmètica de l'array és {:.2f}".format(array.mean()))
            print("La desviació estàndar de l'array és {:.2f}".format(np.std(array)))
    except  AttributeError:
        print("Error: l'input no és un Array")
        
est_array_1d(np.array([1,2,3,4,5]))
est_array_1d(np.array([(1,2,3,4,5),(1,2,3,4,5)]))
est_array_1d('hola')

La longitut de l'array és de 5 elements
El màxim de l'array és 5
El mínim de l'array és 1
La mitjana aritmètica de l'array és 3.00
La desviació estàndar de l'array és 1.41
Error: l'input ha de ser un Array d'una dimensió
Error: l'input no és un Array


## Exercici 2
__Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.__

In [85]:
def quadrat_n(num):
    try:
        rnd.seed(1234)
        array_f = rnd.randint(100,size=(num,num))
        return array_f
    except TypeError:
        print("Error: l'input ha de ser un nombre natural")

print(quadrat_n(1))
print(quadrat_n(2))
print(quadrat_n(3))
print(quadrat_n(4))
print(quadrat_n('gola'))

[[47]]
[[47 83]
 [38 53]]
[[47 83 38]
 [53 76 24]
 [15 49 23]]
[[47 83 38 53]
 [76 24 15 49]
 [23 26 30 43]
 [30 26 58 92]]
Error: l'input ha de ser un nombre natural
None


## Exercici 3
__Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.__

In [57]:
def sum_fil_col_2d(array):
    try:
        if array.ndim == 2:
            print
            print("Els totals per fila són: {}".format(np.sum(a,axis=1)))
            print("Els totals per columna són: {}".format(np.sum(a,axis=0)))
        else:
            print("Error: l'array no és de dues dimensions")
    except AttributeError:
        print("L'input no és un array")

sum_fil_col_2d(np.array([(3,4),(1,1)]))
sum_fil_col_2d(np.array([(3,4),(1,1)],ndmin=3))
sum_fil_col_2d(3)

Els totals per fila són: [7 2]
Els totals per columna són: [4 5]
Error: l'array no és de dues dimensions
L'input no és un array


## Exercici 4
__Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.__

In [97]:
def coef_corr_2a(array1,array2):
    try:
        if len(array1) == len(array2):
            l = len(array1)
            sumx=array1.sum()
            sumy=array2.sum()
            x2=array1**2
            y2=array2**2
            sumx2=x2.sum()
            sumy2=y2.sum()
            xy=array1*array2
            sumxy=xy.sum()
            coef = (l*sumxy-sumx*sumy)/(np.sqrt(l*sumx2 - sumx**2)*np.sqrt(l*sumy2 - sumy**2))
            print("El coeficient de correlació entre els dos arrays és de {:.4f}".format(coef))
        else:
            print("Error: els arrays no tenen la mateixa mida")
    except AttributeError:
        print("Error: algun input no és un array")

coef_corr_2a(np.array([3,4,2]),np.array([1,1,2]))

# Es comprova que s'ha calculat bé amb la una funció de numpy
print(np.corrcoef(np.array([3,4,2]),np.array([1,1,2])))

El coeficient de correlació entre els dos arrays és de -0.8660
[[ 1.        -0.8660254]
 [-0.8660254  1.       ]]
